### ISSUE TITLE
run several commands at once?

### ISSUE THREAD

**Issue by fsardi** [i-vrnv/mikrotik-ssh#3]
This is a great and simple program. How can I run several commands in one call to speed up my code?

**Comment by fsardi** [comment]
Solved: just separate the comands win a ";".  Thanks a lot.

**Comment by i-vrnv** [comment]
Thank you for your comment about the program. I am very glad that you like it! I will update the documentation. 

If you have any more questions or suggestions, feel free to contact me.

**Comment by i-vrnv** [comment]
@fsardi could you provide me an example for the documentation?

**Comment by i-vrnv** [comment]
I think the problem is not actual.
